# Configuration for a wandb sweep
# Running the following command under the hood:

program: scripts/reinforcement_learning/skrl/train.py
description: "recontruction_PPO_sweep"
name: recontruction_PPO_sweep
method: bayes
metric:
  goal: maximize
  name: total_reward
parameters:
  agent.agent.rollouts: 
    values: [64, 32, 16]
  agent.agent.mini_batches: 
    values: [128, 32, 4]
  agent.agent.learning_epochs: 
    values: [1, 3, 5]

command:
  - /isaac-sim/python.sh
  - ${program}
  - "--headless"
  - "--task=Isaac-robot-US-reconstruction-v0"
  - "--algorithm=PPO"
  - ${args_no_hyphens}
