seed: 42

n_timesteps: !!float 20e6
policy: 'MultiInputPolicy'
n_steps: 64 # 16
batch_size: 256
gae_lambda: 0.95
gamma: 0.99
n_epochs: 1 # 20
ent_coef: 0.01
learning_rate: !!float 3e-4
clip_range: !!float 0.2
vf_coef: 1.0
max_grad_norm: 1.0
device: "cuda:0"