seed: 42

rollouts: 16
learning_epochs: 5
mini_batches: 32
discount_factor: 0.99
lambda: 0.95
learning_rate: 1.0e-04
learning_rate_scheduler: KLAdaptiveLR
learning_rate_scheduler_kwargs:
  kl_threshold: 0.008
state_preprocessor: null
state_preprocessor_kwargs: null
value_preprocessor: RunningStandardScaler
value_preprocessor_kwargs: null
random_timesteps: 0
learning_starts: 0
grad_norm_clip: 1.0
ratio_clip: 0.2
value_clip: 0.1
clip_predicted_values: True
entropy_loss_scale: 0.0
value_loss_scale: 1.0
kl_threshold: 0.0
rewards_shaper_scale: 1.0
time_limit_bootstrap: False

cost_limit: 200.0
lagrangian_pid: [0.05, 0.0005, 0.1]
state_dependence: False


# logging and checkpoint
# logging and checkpoint
experiment:
  directory: "surgery_tip_frame"
  experiment_name: "PPOL_default_US_net"
  write_interval: auto
  checkpoint_interval: auto