# Configuration for a wandb sweep
# Running the following command under the hood:

program: scripts/reinforcement_learning/skrl/train.py
description: "surgery_PPO_sweep"
name: surgery_PPO_sweep
method: bayes
metric:
  goal: maximize
  name: total_reward
parameters:
  agent.seed:
    values: [1, 2, 3, 4, 5]

command:
  - /isaac-sim/python.sh
  - ${program}
  - "--headless"
  - "--task=Isaac-robot-US-guided-surgery-v0"
  - "--algorithm=PPO"
  - ${args_no_hyphens}
