# Configuration for a wandb sweep
# Running the following command under the hood:

program: scripts/reinforcement_learning/skrl/train_ppol.py
description: "surgery_PPOl_sweep_cost_250"
name: surgery_PPOl_sweep_cost_250
method: bayes
metric:
  goal: maximize
  name: total_reward
parameters:
  agent.rollouts: 
    values: [64, 32, 16]
  agent.mini_batches: 
    values: [128, 32, 4]
  agent.learning_epochs: 
    values: [1, 3, 5]
  agent.value_loss_scale:
    values: [1.0, 3.0, 10.0]
  

command:
  - /isaac-sim/python.sh
  - ${program}
  - "--headless"
  - "--task=Isaac-robot-US-guided-surgery-v0"
  - ${args_no_hyphens}
